# --- HTTP ---
quarkus.http.port=9000

quarkus.mcp.server.sse.root-path=mcp
quarkus.mcp.server.stdio.enabled=false

# Streamable HTTP sessions
quarkus.mcp.server.auto-ping-interval=10s
quarkus.mcp.server.connection-idle-timeout=8M

# --- gRPC ---
quarkus.grpc.clients.dnaerys.host=db.dnaerys.org
quarkus.grpc.clients.dnaerys.port=443
quarkus.grpc.clients.dnaerys.plain-text=false
quarkus.grpc.clients.dnaerys.ssl.trust-store=certs/dnaerys-trust.pem
quarkus.grpc.clients.dnaerys.flow-control-window=1048576
quarkus.grpc.clients.dnaerys.max-inbound-message-size=10485760

# --- logging ---
quarkus.log.category."org.dnaerys".level=DEBUG
quarkus.log.category."io.grpc".level=INFO
quarkus.log.category."io.netty".level=INFO
quarkus.log.category."org.dnaerys.mcp.toolcalls".level=ERROR
quarkus.log.category."io.quarkiverse.mcp.server.http.runtime.StreamableHttpMcpConnection".level=ERROR

# --- CORS ---
quarkus.http.cors.enabled=true

# --- Dev Profile Overrides ---
%dev.quarkus.mcp.server.stdio.enabled=true
